openapi: 3.0.3
info:
  title: Salesforce AgentForce Opportunity Tool API
  description: API for managing Salesforce opportunities.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /v1/opportunities:
    post:
      summary: Query Salesforce opportunities
      description: Returns a list of opportunities or a mathematical result based on a SOQL query provided in the request body.
      x-sfdc:
        heroku:
          authorization:
            connectedApp: "MyAppLinkConnectedApp"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "SELECT Id, Name, StageName, Amount, CloseDate FROM Opportunity WHERE StageName = 'Prospecting'"
      responses:
        "200":
          description: Success. List of opportunities returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
                  opportunities:
                    type: array
                    items:
                      $ref: "#/components/schemas/Opportunity"
                  mathResult:
                    type: number
                    example: 65500
        "500":
          description: Error or no results found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No opportunities found matching your query."
components:
  schemas:
    Opportunity:
      type: object
      properties:
        Id:
          type: string
          example: "006Ka00000TJEZUIA5"
        Name:
          type: string
          example: "Omega Technologies"
        StageName:
          type: string
          example: "Closed Won"
        Amount:
          type: number
          format: float
          example: 65500
        CloseDate:
          type: string
          format: date
          example: "2025-09-10"
        AccountId:
          type: string
          example: "001Ka00004PqZCIIA3"
        OwnerId:
          type: string
          example: "005Ka000004UsT0IAK"
        Probability:
          type: number
          format: int32
          minimum: 0
          maximum: 100
          example: 100
        Description:
          type: string
          example: "This deal is looking good so far."
